{"name": "test_myoutput", "status": "failed", "statusDetails": {"message": "AssertionError: assert '' == 'hello\\n'\n  + hello", "trace": "capsys = <_pytest.capture.CaptureFixture object at 0x09645490>\n\n    def test_myoutput(capsys):\n        # or use \"capfd\" for fd-level\n        log.debug(\"hello\")\n        sys.stderr.write(\"world\\n\")\n        captured = capsys.readouterr()\n>       assert captured.out == \"hello\\n\"\nE       AssertionError: assert '' == 'hello\\n'\nE         + hello\n\ntests\\test_log\\test_log_2.py:15: AssertionError"}, "attachments": [{"name": "log", "source": "51b2e509-0093-4aac-8bc2-fee7824a479e-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "ec27158b-2886-422d-ad55-0ddd64b5bd54-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "165286a9-cba5-4cfd-8e38-1854af1f20e3-attachment.txt", "type": "text/plain"}], "start": 1557774049050, "stop": 1557774049050, "uuid": "3bd123fe-b9b6-4e31-83e4-2b2dad10e430", "historyId": "f3585727535e24109e5e6000aa6e47cb", "fullName": "tests.test_log.test_log_2#test_myoutput", "labels": [{"name": "parentSuite", "value": "tests.test_log"}, {"name": "suite", "value": "test_log_2"}, {"name": "host", "value": "HenryChang"}, {"name": "thread", "value": "11320-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_log.test_log_2"}]}